### ISSUE TITLE
canvas text input cards invisible

### ISSUE THREAD

**Issue by 1C0D** [polyipseity/obsidian-modules#3] opened 2023-09-01 21:02 UTC
Really strange, but when the plugin is enabled, text into cards is invisible.
It's reappearing after disabling the plugin and a restart

**Comment by polyipseity** [comment] 2023-09-01 23:35
Duplicate of [#2](https://github.com/polyipseity/obsidian-modules/issues/2). The fix is not yet released, however. You need to use BRAT to install the fixed version of the plugin.

**Closed by polyipseity** 2023-09-01 23:35 UTC
Labels: bug, duplicate

**Comment by polyipseity** [comment] 2023-09-06 12:32
Fixed in [2.1.0](https://github.com/polyipseity/obsidian-modules/releases/2.1.0).
